// import Head from "next/head";
// import Image from "next/image";
// import { Geist, Geist_Mono } from "next/font/google";
// import styles from "@/styles/Home.module.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div
//         className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
//       >
//         <main className={styles.main}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js logo"
//             width={180}
//             height={38}
//             priority
//           />
//           <ol>
//             <li>
//               Get started by editing <code>src/pages/index.js</code>.
//             </li>
//             <li>Save and see your changes instantly.</li>
//           </ol>

//           <div className={styles.ctas}>
//             <a
//               className={styles.primary}
//               href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               <Image
//                 className={styles.logo}
//                 src="/vercel.svg"
//                 alt="Vercel logomark"
//                 width={20}
//                 height={20}
//               />
//               Deploy now
//             </a>
//             <a
//               href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//               className={styles.secondary}
//             >
//               Read our docs
//             </a>
//           </div>
//         </main>
//         <footer className={styles.footer}>
//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <Image
//               aria-hidden
//               src="/file.svg"
//               alt="File icon"
//               width={16}
//               height={16}
//             />
//             Learn
//           </a>
//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <Image
//               aria-hidden
//               src="/window.svg"
//               alt="Window icon"
//               width={16}
//               height={16}
//             />
//             Examples
//           </a>
//           <a
//             href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <Image
//               aria-hidden
//               src="/globe.svg"
//               alt="Globe icon"
//               width={16}
//               height={16}
//             />
//             Go to nextjs.org →
//           </a>
//         </footer>
//       </div>
//     </>
//   );
// }

// app/page.js หรือ components/Index.js (ขึ้นกับโครงสร้างโปรเจค)
import { useRouter } from "next/navigation";
import Navbar from "@/components/Navbar";
import { useFormContext } from "@/context/FormContext";
import { Box, Button, Typography, Container, Card } from "@mui/material";
import {
  Description as FileTextIcon,
  Share as ShareIcon,
  BarChart as BarChartIcon,
} from "@mui/icons-material";

const Index = () => {
  const { createForm } = useFormContext();
  const router = useRouter();

  const handleCreateForm = () => {
    const formId = createForm();
    router.push(`/formbuilder?formId=${formId}`);
  };

  return (
    <Box sx={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
      <Navbar />

      <Box component="main" sx={{ flex: 1, py: 6, px: 2, mt: 8 }}>
        <Container maxWidth="lg">
          <Box
            sx={{ textAlign: "center", maxWidth: "48rem", mx: "auto", mb: 8 }}
          >
            <Typography
              variant="h4"
              sx={{ fontWeight: "bold", color: "grey.900", mb: 3 }}
            >
              สร้างแบบฟอร์มออนไลน์ฟรีและเผยแพร่ได้ทันที
            </Typography>
            <Typography variant="h6" sx={{ color: "grey.600", mb: 4 }}>
              ออกแบบแบบฟอร์มที่เป็นมิตรกับผู้ใช้ รวบรวมข้อมูลอย่างมีประสิทธิภาพ
              และดูผลลัพธ์แบบเรียลไทม์
            </Typography>

            <Button
              variant="contained"
              size="large"
              onClick={handleCreateForm}
              sx={{ bgcolor: "#003092", "&:hover": { bgcolor: "#003092" } }}
            >
              เริ่มสร้างแบบฟอร์มใหม่
            </Button>
          </Box>

          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: { xs: "1fr", md: "1fr 1fr 1fr" },
              gap: 4,
            }}
          >
            <Box
              component={Card}
              sx={{
                bgcolor: "white",
                p: 3,
                borderRadius: 2,
                // boxShadow: 1,
                border: "1px solid",
                borderColor: "grey.200",
              }}
            >
              <Box
                sx={{
                  bgcolor: "blue.50",
                  p: 1.5,
                  borderRadius: "50%",
                  width: 48,
                  height: 48,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  mb: 2,
                }}
              >
                <FileTextIcon
                  sx={{ color: "blue.500", width: 24, height: 24 }}
                />
              </Box>
              <Typography variant="h6" sx={{ fontWeight: "medium", mb: 1 }}>
                การสร้างสรรค์ที่ไร้ขีดจำกัด
              </Typography>
              <Typography sx={{ color: "grey.600" }}>
                ออกแบบแบบฟอร์มไม่จำกัดพร้อมคำถามหลากหลายประเภท
              </Typography>
            </Box>

            <Box
              component={Card}
              sx={{
                bgcolor: "white",
                p: 3,
                borderRadius: 2,
                // boxShadow: 1,
                border: "1px solid",
                borderColor: "grey.200",
              }}
            >
              <Box
                sx={{
                  bgcolor: "blue.50",
                  p: 1.5,
                  borderRadius: "50%",
                  width: 48,
                  height: 48,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  mb: 2,
                }}
              >
                <ShareIcon sx={{ color: "blue.500", width: 24, height: 24 }} />
              </Box>
              <Typography variant="h6" sx={{ fontWeight: "medium", mb: 1 }}>
                แบ่งปันทันที
              </Typography>
              <Typography sx={{ color: "grey.600" }}>
                เผยแพร่แบบฟอร์มผ่าน URL และแบ่งปันได้อย่างง่ายดาย
              </Typography>
            </Box>

            <Box
              component={Card}
              sx={{
                bgcolor: "white",
                p: 3,
                borderRadius: 2,
                // boxShadow: 1,
                border: "1px solid",
                borderColor: "grey.200",
              }}
            >
              <Box
                sx={{
                  bgcolor: "blue.50",
                  p: 1.5,
                  borderRadius: "50%",
                  width: 48,
                  height: 48,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  mb: 2,
                }}
              >
                <BarChartIcon
                  sx={{ color: "blue.500", width: 24, height: 24 }}
                />
              </Box>
              <Typography variant="h6" sx={{ fontWeight: "medium", mb: 1 }}>
                วิเคราะห์ผลลัพธ์
              </Typography>
              <Typography sx={{ color: "grey.600" }}>
                ดูและวิเคราะห์คำตอบแบบฟอร์มอย่างละเอียด
              </Typography>
            </Box>
          </Box>
        </Container>
      </Box>

      <Box component="footer" sx={{ bgcolor: "grey.50", py: 4 }}>
        <Container maxWidth="lg">
          <Typography sx={{ textAlign: "center", color: "grey.500" }}>
            © {new Date().getFullYear()} appform - Online Servey Form Builder
            System Powered by AppLab Tech.
          </Typography>
        </Container>
      </Box>
    </Box>
  );
};

export default Index;
